# Generated by Django 5.2.6 on 2025-09-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('buying_price', models.IntegerField(help_text='This field will help to calculate profits')),
                ('selling_price', models.IntegerField()),
                ('discount_price', models.IntegerField(help_text='This amount will appear to subscribed users')),
                ('quantity', models.IntegerField(default=1)),
                ('product_image', models.ImageField(upload_to='product_display_image/')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
